Replace `catch` with `try-catch` to fix the compilation error in OTP-29
Fix the following compilation errors:

```bash
$ make
src/ibrowse_lib.erl:65:10: 'catch ...' is deprecated; please use 'try ... catch ... end' instead.
Compile directive 'nowarn_deprecated_catch' can be used to suppress
warnings in selected modules.
%   65|     case catch decode_rfc822_date_1(string:tokens(String, ", \t\r\n")) of
%     |
```